/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'id' : IDL.Text,
  'loanFee' : IDL.Float64,
  'loanInterest' : IDL.Float64,
  'loanAmount' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'createdBy' : IDL.Text,
  'isActive' : IDL.Bool,
  'loanType' : IDL.Text,
  'serialNumber' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'lineCategoryId' : IDL.Text,
});
export const EMIPayment = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Text,
  'recordedBy' : IDL.Text,
  'paymentDate' : IDL.Text,
  'customerId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LineCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateCustomer' : IDL.Func([Customer], [], []),
  'addOrUpdateEMIPayment' : IDL.Func([EMIPayment], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteEMIPayment' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getEMIPayments' : IDL.Func([], [IDL.Vec(EMIPayment)], ['query']),
  'getLineCategories' : IDL.Func([], [IDL.Vec(LineCategory)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setLineCategories' : IDL.Func([IDL.Vec(LineCategory)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'loanFee' : IDL.Float64,
    'loanInterest' : IDL.Float64,
    'loanAmount' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'createdBy' : IDL.Text,
    'isActive' : IDL.Bool,
    'loanType' : IDL.Text,
    'serialNumber' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'lineCategoryId' : IDL.Text,
  });
  const EMIPayment = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Text,
    'recordedBy' : IDL.Text,
    'paymentDate' : IDL.Text,
    'customerId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LineCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateCustomer' : IDL.Func([Customer], [], []),
    'addOrUpdateEMIPayment' : IDL.Func([EMIPayment], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteEMIPayment' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getEMIPayments' : IDL.Func([], [IDL.Vec(EMIPayment)], ['query']),
    'getLineCategories' : IDL.Func([], [IDL.Vec(LineCategory)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setLineCategories' : IDL.Func([IDL.Vec(LineCategory)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };