/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'id' : IDL.Text,
  'loanFee' : IDL.Float64,
  'loanInterest' : IDL.Float64,
  'loanAmount' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'createdBy' : IDL.Text,
  'isActive' : IDL.Bool,
  'loanType' : IDL.Text,
  'serialNumber' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'lineCategoryId' : IDL.Text,
});
export const EMIPayment = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Text,
  'recordedBy' : IDL.Text,
  'paymentDate' : IDL.Text,
  'customerId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LineCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const AgentAccount = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'assignedLines' : IDL.Vec(IDL.Text),
});
export const SavedReport = IDL.Record({
  'id' : IDL.Text,
  'reportDate' : IDL.Text,
  'lineName' : IDL.Text,
  'preAmount' : IDL.Float64,
  'collection' : IDL.Float64,
  'loanFee' : IDL.Float64,
  'lending' : IDL.Float64,
  'expense' : IDL.Float64,
  'dynLeftJson' : IDL.Text,
  'dynRightJson' : IDL.Text,
  'leftTotal' : IDL.Float64,
  'rightTotal' : IDL.Float64,
  'reminder' : IDL.Float64,
  'savedAt' : IDL.Text,
  'savedBy' : IDL.Text,
});
export const CustomerMedia = IDL.Record({
  'photoUrl' : IDL.Text,
  'idProofUrls' : IDL.Vec(IDL.Text),
});
const CustomerTimestampEntry = IDL.Tuple(IDL.Text, IDL.Text);
const CustomerMediaEntry = IDL.Tuple(IDL.Text, CustomerMedia);

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateCustomer' : IDL.Func([Customer], [], []),
  'addOrUpdateEMIPayment' : IDL.Func([EMIPayment], [], []),
  'addOrUpdateSavedReport' : IDL.Func([SavedReport], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteEMIPayment' : IDL.Func([IDL.Text], [], []),
  'deleteSavedReport' : IDL.Func([IDL.Text], [], []),
  'deleteCustomerMedia' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getEMIPayments' : IDL.Func([], [IDL.Vec(EMIPayment)], ['query']),
  'getAgentAccounts' : IDL.Func([], [IDL.Vec(AgentAccount)], ['query']),
  'getLineCategories' : IDL.Func([], [IDL.Vec(LineCategory)], ['query']),
  'getSavedReports' : IDL.Func([], [IDL.Vec(SavedReport)], ['query']),
  'getCustomerTimestamps' : IDL.Func([], [IDL.Vec(CustomerTimestampEntry)], ['query']),
  'getCustomerMedia' : IDL.Func([], [IDL.Vec(CustomerMediaEntry)], ['query']),
  'getLockedLines' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setCustomers' : IDL.Func([IDL.Vec(Customer)], [], []),
  'setEMIPayments' : IDL.Func([IDL.Vec(EMIPayment)], [], []),
  'setLineCategories' : IDL.Func([IDL.Vec(LineCategory)], [], []),
  'setAgentAccounts' : IDL.Func([IDL.Vec(AgentAccount)], [], []),
  'setSavedReports' : IDL.Func([IDL.Vec(SavedReport)], [], []),
  'setCustomerTimestamps' : IDL.Func([IDL.Vec(CustomerTimestampEntry)], [], []),
  'setLockedLines' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setCustomerMedia' : IDL.Func([IDL.Text, CustomerMedia], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'loanFee' : IDL.Float64,
    'loanInterest' : IDL.Float64,
    'loanAmount' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'createdBy' : IDL.Text,
    'isActive' : IDL.Bool,
    'loanType' : IDL.Text,
    'serialNumber' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'lineCategoryId' : IDL.Text,
  });
  const EMIPayment = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Text,
    'recordedBy' : IDL.Text,
    'paymentDate' : IDL.Text,
    'customerId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LineCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const AgentAccount = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'assignedLines' : IDL.Vec(IDL.Text),
  });
  const SavedReport = IDL.Record({
    'id' : IDL.Text,
    'reportDate' : IDL.Text,
    'lineName' : IDL.Text,
    'preAmount' : IDL.Float64,
    'collection' : IDL.Float64,
    'loanFee' : IDL.Float64,
    'lending' : IDL.Float64,
    'expense' : IDL.Float64,
    'dynLeftJson' : IDL.Text,
    'dynRightJson' : IDL.Text,
    'leftTotal' : IDL.Float64,
    'rightTotal' : IDL.Float64,
    'reminder' : IDL.Float64,
    'savedAt' : IDL.Text,
    'savedBy' : IDL.Text,
  });
  const CustomerMedia = IDL.Record({
    'photoUrl' : IDL.Text,
    'idProofUrls' : IDL.Vec(IDL.Text),
  });
  const CustomerTimestampEntry = IDL.Tuple(IDL.Text, IDL.Text);
  const CustomerMediaEntry = IDL.Tuple(IDL.Text, CustomerMedia);
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateCustomer' : IDL.Func([Customer], [], []),
    'addOrUpdateEMIPayment' : IDL.Func([EMIPayment], [], []),
    'addOrUpdateSavedReport' : IDL.Func([SavedReport], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteEMIPayment' : IDL.Func([IDL.Text], [], []),
    'deleteSavedReport' : IDL.Func([IDL.Text], [], []),
    'deleteCustomerMedia' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getEMIPayments' : IDL.Func([], [IDL.Vec(EMIPayment)], ['query']),
    'getAgentAccounts' : IDL.Func([], [IDL.Vec(AgentAccount)], ['query']),
    'getLineCategories' : IDL.Func([], [IDL.Vec(LineCategory)], ['query']),
    'getSavedReports' : IDL.Func([], [IDL.Vec(SavedReport)], ['query']),
    'getCustomerTimestamps' : IDL.Func([], [IDL.Vec(CustomerTimestampEntry)], ['query']),
    'getCustomerMedia' : IDL.Func([], [IDL.Vec(CustomerMediaEntry)], ['query']),
    'getLockedLines' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setCustomers' : IDL.Func([IDL.Vec(Customer)], [], []),
    'setEMIPayments' : IDL.Func([IDL.Vec(EMIPayment)], [], []),
    'setLineCategories' : IDL.Func([IDL.Vec(LineCategory)], [], []),
    'setAgentAccounts' : IDL.Func([IDL.Vec(AgentAccount)], [], []),
    'setSavedReports' : IDL.Func([IDL.Vec(SavedReport)], [], []),
    'setCustomerTimestamps' : IDL.Func([IDL.Vec(CustomerTimestampEntry)], [], []),
    'setLockedLines' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setCustomerMedia' : IDL.Func([IDL.Text, CustomerMedia], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
