/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : string,
  'loanFee' : number,
  'loanInterest' : number,
  'loanAmount' : number,
  'name' : string,
  'createdAt' : string,
  'createdBy' : string,
  'isActive' : boolean,
  'loanType' : string,
  'serialNumber' : string,
  'address' : string,
  'phone' : string,
  'lineCategoryId' : string,
}
export interface EMIPayment {
  'id' : string,
  'createdAt' : string,
  'recordedBy' : string,
  'paymentDate' : string,
  'customerId' : string,
  'amount' : number,
}
export interface LineCategory { 'id' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateCustomer' : ActorMethod<[Customer], undefined>,
  'addOrUpdateEMIPayment' : ActorMethod<[EMIPayment], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteEMIPayment' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getEMIPayments' : ActorMethod<[], Array<EMIPayment>>,
  'getLineCategories' : ActorMethod<[], Array<LineCategory>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setLineCategories' : ActorMethod<[Array<LineCategory>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];