export const labels = {
  en: {
    appName: "Finance Pro",
    dashboard: "Dashboard",
    addEntry: "Add Entry",
    updateEmi: "Update EMI",
    records: "Records",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",
    login: "Login",
    username: "Username",
    password: "Password",
    totalCustomers: "Total Customers",
    activeLoans: "Active Loans",
    totalLoanAmount: "Total Loan Amount",
    totalEmiCollected: "Total EMI Collected",
    todayCollection: "Today's Collection",
    recentActivity: "Recent Activity",
    serialNumber: "Serial Number",
    customerName: "Customer Name",
    phone: "Phone",
    address: "Address",
    loanAmount: "Loan Amount",
    loanInterest: "Loan Interest (%)",
    loanType: "Loan Type",
    lineCategory: "Line Category",
    loanRepayAmount: "Loan Repay Amount",
    paidAmount: "Paid Amount",
    outstandingAmount: "Outstanding Amount",
    loanStatus: "Status",
    emiHistory: "EMI History",
    searchCustomer: "Search by name, serial or address...",
    filterByLine: "Filter by Line",
    preAmount: "Pre Amount",
    collection: "Collection",
    loanFee: "Loan Fee",
    lending: "Lending",
    expense: "Expense",
    reminder: "Reminder",
    addField: "+ Add Field",
    exportExcel: "Export to Excel",
    saveReport: "Save Report",
    savedReports: "Saved Reports",
    noSavedReports: "No saved reports yet",
    reportSaved: "Report saved successfully",
    reportAlreadySaved: "Report generated and Saved Already",
    saveEmi: "Save EMI",
    date: "Date",
    amount: "Amount",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    changePassword: "Change Password",
    manageAgents: "Manage Agents",
    assignLines: "Assign Lines",
    renameLines: "Rename Lines",
    addAgent: "Add Agent",
    addLine: "Add Line",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    loanTypePre: "Pre (ஃபைனான்ஸ்)",
    loanTypePost: "Post (கந்து)",
    all: "All",
    active: "Active",
    completed: "Completed",
    role: "Role",
    agent: "Agent",
    admin: "Admin",
    lines: "Lines",
    general: "General",
    agents: "Agents",
    selectLine: "Select Line",
    selectDate: "Select Date",
    noCustomers: "No customers found",
    emiSaved: "EMI saved successfully",
    emiUpdated: "EMI updated successfully",
    alreadyPaid: "EMI already recorded for this customer today",
    invalidDate: "Only current date allowed",
    submit: "Submit",
    viewDetails: "View Details",
    close: "Close",
    customerAdded: "Customer added successfully",
    fillRequired: "Please fill all required fields",
    enterValidAmount: "Enter a valid amount",
    backupRestored: "Data restored successfully",
    invalidBackupFile: "Invalid backup file format",
    backupReadError: "Could not read the backup file",
    uploadToCloud: "Upload to Cloud",
    uploadSuccess: "Upload Successful",
    uploadFail: "Upload Unsuccessful",
    uploadSuccessMsg: "All data has been uploaded to cloud successfully.",
    uploadFailMsg:
      "Failed to upload data to cloud. Please check your connection and try again.",
    enableDashboard: "Enable Dashboard",
    dashboardAccess: "Dashboard Access",
    allLines: "All Lines",
  },
  ta: {
    appName: "ஃபைனான்ஸ் ப்ரோ",
    dashboard: "டாஷ்போர்டு",
    addEntry: "புதிய பதிவு",
    updateEmi: "EMI புதுப்பி",
    records: "பதிவுகள்",
    reports: "திட்டம்",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    login: "உள்நுழைவு",
    username: "பயனர் பெயர்",
    password: "கடவுச்சொல்",
    totalCustomers: "மொத்த வாடிக்கையாளர்கள்",
    activeLoans: "செயலில் உள்ள கடன்கள்",
    totalLoanAmount: "மொத்த கடன் தொகை",
    totalEmiCollected: "மொத்த EMI வசூல்",
    todayCollection: "இன்றைய வசூல்",
    recentActivity: "சமீபத்திய செயல்பாடு",
    serialNumber: "வரிசை எண்",
    customerName: "வாடிக்கையாளர் பெயர்",
    phone: "தொலைபேசி",
    address: "முகவரி",
    loanAmount: "கடன் தொகை",
    loanInterest: "வட்டி (%)",
    loanType: "கடன் வகை",
    lineCategory: "வரிசை பிரிவு",
    loanRepayAmount: "திருப்பிச் செலுத்த வேண்டிய தொகை",
    paidAmount: "செலுத்திய தொகை",
    outstandingAmount: "நிலுவைத் தொகை",
    loanStatus: "நிலை",
    emiHistory: "EMI வரலாறு",
    searchCustomer: "பெயர், வரிசை அல்லது முகவரி மூலம் தேடு...",
    filterByLine: "வரிசையால் வடிகட்டு",
    preAmount: "முன் இருப்பு",
    collection: "வசூல்",
    loanFee: "மகிமை",
    lending: "அடைப்பு",
    expense: "செலவு",
    reminder: "மீதி இருப்பு",
    addField: "+ புலம் சேர்",
    exportExcel: "Excel ஏற்றுமதி",
    saveReport: "அறிக்கை சேமி",
    savedReports: "சேமித்த அறிக்கைகள்",
    noSavedReports: "சேமித்த அறிக்கைகள் இல்லை",
    reportSaved: "அறிக்கை வெற்றிகரமாக சேமிக்கப்பட்டது",
    reportAlreadySaved: "அறிக்கை ஏற்கனவே உருவாக்கப்பட்டு சேமிக்கப்பட்டது",
    saveEmi: "EMI சேமி",
    date: "தேதி",
    amount: "தொகை",
    save: "சேமி",
    cancel: "ரத்து",
    edit: "திருத்து",
    delete: "நீக்கு",
    add: "சேர்",
    changePassword: "கடவுச்சொல் மாற்று",
    manageAgents: "முகவர்களை நிர்வகி",
    assignLines: "வரிசைகள் ஒதுக்கு",
    renameLines: "வரிசைகள் மறுபெயரிடு",
    addAgent: "முகவர் சேர்",
    addLine: "வரிசை சேர்",
    currentPassword: "தற்போதைய கடவுச்சொல்",
    newPassword: "புதிய கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல் உறுதிப்படுத்து",
    loanTypePre: "ஃபைனான்ஸ்",
    loanTypePost: "கந்து",
    all: "அனைத்தும்",
    active: "செயலில்",
    completed: "முடிந்தது",
    role: "பங்கு",
    agent: "முகவர்",
    admin: "நிர்வாகி",
    lines: "வரிசைகள்",
    general: "பொது",
    agents: "முகவர்கள்",
    selectLine: "வரிசை தேர்வு",
    selectDate: "தேதி தேர்வு",
    noCustomers: "வாடிக்கையாளர்கள் இல்லை",
    emiSaved: "EMI வெற்றிகரமாக சேமிக்கப்பட்டது",
    emiUpdated: "EMI வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
    alreadyPaid: "இன்று இந்த வாடிக்கையாளருக்கு EMI பதிவு செய்யப்பட்டது",
    invalidDate: "தற்போதைய தேதி மட்டுமே அனுமதிக்கப்படுகிறது",
    submit: "சமர்ப்பி",
    viewDetails: "விவரங்கள் பார்",
    close: "மூடு",
    customerAdded: "வாடிக்கையாளர் வெற்றிகரமாக சேர்க்கப்பட்டது",
    fillRequired: "அனைத்து கட்டாய புலங்களையும் நிரப்பவும்",
    enterValidAmount: "சரியான தொகை உள்ளிடவும்",
    backupRestored: "தரவு வெற்றிகரமாக மீட்டமைக்கப்பட்டது",
    invalidBackupFile: "தவறான கோப்பு வடிவம்",
    backupReadError: "கோப்பை படிக்க முடியவில்லை",
    uploadToCloud: "Cloud-ல் பதிவேற்று",
    uploadSuccess: "பதிவேற்றம் வெற்றிகரமாக முடிந்தது",
    uploadFail: "பதிவேற்றம் தோல்வியடைந்தது",
    uploadSuccessMsg: "அனைத்து தரவும் cloud-ல் வெற்றிகரமாக பதிவேற்றப்பட்டது.",
    uploadFailMsg:
      "Cloud-ல் பதிவேற்ற முடியவில்லை. இணைப்பை சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    enableDashboard: "டாஷ்போர்டு இயக்கு",
    dashboardAccess: "டாஷ்போர்டு அணுகல்",
    allLines: "அனைத்து வரிசைகள்",
  },
};

export type LabelKey = keyof typeof labels.en;
